import { AlertTriangle } from 'lucide-react'
import type { Category } from '@/types/database'

// ─── Disclaimer copy per category ────────────────────────────────────────────

const DISCLAIMERS: Partial<Record<string, { heading: string; body: string }>> = {
  'legal-documents': {
    heading: 'Legal Disclaimer',
    body:
      'The documents generated by this tool are for informational purposes only and do not constitute legal advice. Laws vary by state and jurisdiction within the United States. Always consult a licensed US attorney before signing or relying on any legal document.',
  },
  'finance-tax': {
    heading: 'Financial & Tax Disclaimer',
    body:
      'This tool provides general financial information only and is not a substitute for professional tax or financial advice. Tax laws change frequently. Consult a licensed CPA, tax advisor, or financial professional for guidance specific to your situation under US federal and state law.',
  },
  'hr-recruitment': {
    heading: 'HR & Employment Disclaimer',
    body:
      'Documents generated here are templates and may not comply with all applicable federal, state, or local employment laws in the United States. Always have HR policies and employment documents reviewed by a qualified US employment attorney before use.',
  },
  'real-estate': {
    heading: 'Real Estate Disclaimer',
    body:
      'Real estate laws, disclosure requirements, and contract terms vary significantly across US states. This tool does not replace the advice of a licensed real estate attorney or agent. Always consult a qualified professional before entering into any real estate transaction.',
  },
  'small-business': {
    heading: 'Business Disclaimer',
    body:
      'Business documents and plans generated by this tool are for reference purposes only. Consult a licensed business attorney or accountant before making business decisions or executing agreements under US federal or state law.',
  },
}

interface DisclaimerProps {
  categorySlug: string
  className?:   string
}

export default function Disclaimer({ categorySlug, className = '' }: DisclaimerProps) {
  const disclaimer = DISCLAIMERS[categorySlug]
  if (!disclaimer) return null

  return (
    <aside
      role="note"
      aria-label={disclaimer.heading}
      className={`flex gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4 ${className}`}
    >
      <AlertTriangle
        size={16}
        className="mt-0.5 shrink-0 text-amber-500"
        aria-hidden
      />
      <div className="text-xs text-amber-800 leading-relaxed">
        <p className="font-semibold mb-1">{disclaimer.heading}</p>
        <p>{disclaimer.body}</p>
      </div>
    </aside>
  )
}
